### ISSUE TITLE
Mockery not cleaning up after itself properly

### ISSUE THREAD

**Issue by gowerc** [r-lib/mockery#57]
Hi,

I'm really not sure what the exactly what is going here but I am running into a bug where due to a combination of using a package + exporting functions mockery isn't cleaning up after itself. I managed to create the smallest repex of the problem that I could manage here: https://github.com/gowerc/test-mockery

For reference the main unit tests in that repo are:

```
test_that("test - 1",  {
    x <- 1
    class(x) <- "meth"
    mocky <- mockery::mock(2)
    mockery::stub(main, "some_other_fun", mocky, depth = 2)
    expect_equal(main(x), 2)
})


test_that("test - 2",  {
    expect_equal(get_list_of_fun(), list("myfun" = somefun))
})
```

When calling `devtools::test()` on that project I get:

```
==> devtools::test()

ℹ Loading testMock
ℹ Testing testMock
✓ | F W S  OK | Context
x | 1       1 | mock                                                                                                   
───────────────────────────────────────────────────────────────────────────────────────
Failure (test-mock.R:12:5): test - 2
get_list_of_fun() (`actual`) not equal to list(myfun = somefun) (`expected`).

`environment(actual$myfun)` is <env:0x7f9ac07c5b00>
`environment(expected$myfun)` is <env:namespace:testMock>
───────────────────────────────────────────────────────────────────────────────────────

══ Results ════════════════════════════════════════════════════════════════════════════
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 1 ]
```

Note that the error is coming from "test -2" which doesn't use mockery i.e. the changes mockery has made in the first unit test have bled over to the second unit test.  My expectation (sorry if I have this wrong) was that any changes made by mockery should be localised to the specific `test_that()` block.

**Comment by njtierney** [comment]
I am getting similar behaviour here, with mockery leaking over into other parts of the code, which is causing many tests to fail in ways that they shouldn't

https://github.com/greta-dev/greta/runs/5197084911?check_suite_focus=true#step:12:2563

**Comment by njtierney** [comment]
I've given a bit more detail in this RStudio Community post here: https://community.rstudio.com/t/mockery-stub-is-creating-mocking-functions-that-persist-into-other-tests/129259

**Comment by FlorianMyronStork** [comment]
@gowerc 
Hi, I am using mockery only since a few months and never encountered such behavior.

Two suggestions:
1) Must it be called with `depth = 2`? If not, try to leave this argument alone.

2) I am not using `test_that("assumtion", {code}) semantics. I tend to use `describe("what to describe?", {it("does stuff", {code})})`

It's a bit more verbose, but maybe it's a bit safer with `mockery`

Does this:
```describe("test - 1",  {
  it("does stuff i expect", {
    x <- 1
    class(x) <- "meth"
    mocky <- mockery::mock(2)
    mockery::stub(main, "some_other_fun", mocky, depth = 2)
    expect_equal(main(x), 2)
  })
})


describe("test - 2",  {
  it("does stuff without being interfered by my other mocks", {
    expect_equal(get_list_of_fun(), list("myfun" = somefun))
  })
})```

Some other steps to test if it REALLY is mockerys fault:

1) Does the 2nd test still fail, when the first wasn't run? - Then it's got nothing to do with mockery
2) Have you tryed to add a simple `print(get_list_of_fun())' into your test to get an idea of what it really returns within the test? Maybe the assumption wasn't precise.
3) Do you encounter different test-behaviour when running the test manually vs. via `devtools::test()`? If so, this might also be due to `devtools::test()`-behaviour as it temporarily changes some settings with might mess with assumtions made under the impression that there shouldn't be any difference in the ways tests can be run.

No offence! I am sure you tryed all you could think of, I am just giving advice based on my own mistakes :)

Good coding!

**Comment by hadley** [comment]
We now recommend that you use `testthat::local_mocked_bindings()` instead of mockery; one of the problems it fixes is correctly scoping the mocking.
